---
- name: pruebas de implementacion de ansible
  hosts: localhost
  gather_facts: false

  tasks:

    - name: prueba
      debug:
        msg: "Hola Mundo"
        
    - name: ubicacion playbooks
      shell: "pwd;ls -l"
      register: localiza

    - name: mostrar ubicacion
      debug:
        msg: "{{ localiza }}"

    - name: mostrar ubicacion
      debug:
        msg: "{{ localiza }}"

    - name: Heredar variable
      ansible.builtin.set_stats:
        data:
          localiza_heredado: "{{ localiza }}"
