---
- name: pruebas de implementacion de ansible
  hosts: localhost
  gather_facts: false

  tasks:

    - name: prueba
      debug:
        msg: "Hola Mundo"
        
    - name: ubicacion playbooks
      command: "pwd;ls -l"
      register: localiza

    - name: mostrar ubicacion
      debug:
        msg: "{{ localiza }}"      
